zuul:
  routes:
    consumer:
      path: /consumer/**
      url: http://localhost:8001/
#      serviceId: CONSUMER
#      stripPrefix: true 
    provider: 
      path: /provider/**
      serviceId: PROVIDER


